spring:
  application:
    name: springboot-single-app
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8085

logging:
  level:
    org.example.springbootsingleapp: DEBUG
